try:
    import os
    import string
    import sys
except ImportError as e:
    sys.exit("An error occurred while importing the required modules.", e)

# This script is used to find log files that are generated by Robert Space Industries' Star Citizen game.

# Function to search for log files.
def find_log_files():
    # Create a list to store the log files.
    log_files = []

    # Loop through the current directory and all subdirectories.
    for drive_letter in string.ascii_uppercase:
        potential_path = f"{drive_letter}:\\Program Files\\Roberts Space Industries\\StarCitizen\\LIVE\\Game.log"
        if os.path.exists(potential_path):
            print(f"Found log file at {potential_path}")
            log_files.append(potential_path)
            break
        else:
            print(f"Could not find log file at {potential_path}")


    # Return the list of log files.
    return log_files

def print_log_files(log_files):
    with open("log_contents.txt", "w") as output_file:
        for log_file in log_files:
            with open(log_file, "r") as file:
                output_file.write(f"Contents of {log_file}:\n")
                output_file.write(file.read())
                output_file.write("\n--- End of file ---\n\n")

def main():
    try: 
        log_files = find_log_files()
        if log_files:
            print("Log files found!")
            print_log_files(log_files)
            print("The contents of the log files have been written to log_contents.txt.")
            try: 
                os.path.exists("log_contents.txt")
                if os.path.exists("log_contents.txt"):
                    print("Opening log_contents.txt...")
                    os.startfile("log_contents.txt")
            except Exception as e:
                print("An error occurred while trying to open log_contents.txt.", e)
        else:
            print("No log files found.")
    except Exception as e:
        print("An error occurred.", e)

main()